# Generated by Django 4.2.3 on 2023-07-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_sidebar',
            name='doc_title_en',
        ),
        migrations.RemoveField(
            model_name='header_sidebar',
            name='doc_title_ru',
        ),
        migrations.RemoveField(
            model_name='header_sidebar',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='header_sidebar',
            name='phone_number_ru',
        ),
    ]
