# Generated by Django 4.2.3 on 2023-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_header_sidebar_doc_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Background')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('colored_title', models.CharField(max_length=50, verbose_name='Colored Title')),
                ('colored_title_ru', models.CharField(max_length=50, null=True, verbose_name='Colored Title')),
                ('colored_title_en', models.CharField(max_length=50, null=True, verbose_name='Colored Title')),
                ('subtitle', models.CharField(max_length=70, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(max_length=70, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(max_length=70, null=True, verbose_name='Subtitle')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('btn_name1_ru', models.CharField(max_length=40, null=True, verbose_name='Button Name 1')),
                ('btn_name1_en', models.CharField(max_length=40, null=True, verbose_name='Button Name 1')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
                ('btn_name2_ru', models.CharField(max_length=40, null=True, verbose_name='Button Name 2')),
                ('btn_name2_en', models.CharField(max_length=40, null=True, verbose_name='Button Name 2')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
    ]
