# Generated by Django 4.2.3 on 2023-07-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='colored_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='colored_title_ru',
        ),
    ]
