# Generated by Django 4.2.3 on 2023-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle1')),
                ('subtitle1_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle1')),
                ('subtitle1_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle1')),
                ('title1', models.CharField(max_length=80, verbose_name='Title 1')),
                ('title1_ru', models.CharField(max_length=80, null=True, verbose_name='Title 1')),
                ('title1_en', models.CharField(max_length=80, null=True, verbose_name='Title 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle2')),
                ('subtitle2_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle2')),
                ('subtitle2_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle2')),
                ('title2', models.CharField(max_length=80, verbose_name='Title 2')),
                ('title2_ru', models.CharField(max_length=80, null=True, verbose_name='Title 2')),
                ('title2_en', models.CharField(max_length=80, null=True, verbose_name='Title 2')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Subtitle3')),
                ('subtitle3_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle3')),
                ('subtitle3_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle3')),
                ('title3', models.CharField(max_length=80, verbose_name='Title 3')),
                ('title3_ru', models.CharField(max_length=80, null=True, verbose_name='Title 3')),
                ('title3_en', models.CharField(max_length=80, null=True, verbose_name='Title 3')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Subtitle4')),
                ('subtitle4_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle4')),
                ('subtitle4_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle4')),
                ('title4', models.CharField(max_length=80, verbose_name='Title 4')),
                ('title4_ru', models.CharField(max_length=80, null=True, verbose_name='Title 4')),
                ('title4_en', models.CharField(max_length=80, null=True, verbose_name='Title 4')),
                ('subtitle5', models.CharField(max_length=50, verbose_name='Subtitle5')),
                ('subtitle5_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle5')),
                ('subtitle5_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle5')),
                ('title5', models.CharField(max_length=80, verbose_name='Title 5')),
                ('title5_ru', models.CharField(max_length=80, null=True, verbose_name='Title 5')),
                ('title5_en', models.CharField(max_length=80, null=True, verbose_name='Title 5')),
                ('subtitle6', models.CharField(max_length=50, verbose_name='Subtitle6')),
                ('subtitle6_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle6')),
                ('subtitle6_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle6')),
                ('title6', models.CharField(max_length=80, verbose_name='Title 6')),
                ('title6_ru', models.CharField(max_length=80, null=True, verbose_name='Title 6')),
                ('title6_en', models.CharField(max_length=80, null=True, verbose_name='Title 6')),
                ('subtitle7', models.CharField(max_length=50, verbose_name='Subtitle7')),
                ('subtitle7_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle7')),
                ('subtitle7_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle7')),
                ('title7', models.CharField(max_length=80, verbose_name='Title 7')),
                ('title7_ru', models.CharField(max_length=80, null=True, verbose_name='Title 7')),
                ('title7_en', models.CharField(max_length=80, null=True, verbose_name='Title 7')),
                ('subtitle8', models.CharField(max_length=50, verbose_name='Subtitle8')),
                ('subtitle8_ru', models.CharField(max_length=50, null=True, verbose_name='Subtitle8')),
                ('subtitle8_en', models.CharField(max_length=50, null=True, verbose_name='Subtitle8')),
                ('title8', models.CharField(max_length=80, verbose_name='Title 8')),
                ('title8_ru', models.CharField(max_length=80, null=True, verbose_name='Title 8')),
                ('title8_en', models.CharField(max_length=80, null=True, verbose_name='Title 8')),
            ],
        ),
    ]
