# Generated by Django 4.2.3 on 2023-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='type_ru',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='category_en',
            field=models.CharField(max_length=50, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='category'),
        ),
    ]
