# Generated by Django 4.2.3 on 2023-07-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_menu_type_remove_menu_type_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('recipe', models.TextField(verbose_name='Recipe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
            options={
                'verbose_name': 'Menu Content',
                'verbose_name_plural': 'Menu Content',
            },
        ),
    ]
