# Generated by Django 4.2.3 on 2023-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_menucontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucontent',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='menucontent',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='menucontent',
            name='recipe_en',
            field=models.TextField(null=True, verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='menucontent',
            name='recipe_ru',
            field=models.TextField(null=True, verbose_name='Recipe'),
        ),
    ]
