# Generated by Django 4.2.3 on 2023-07-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_menucontent_name_en_menucontent_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucontent',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
