# Generated by Django 4.2.3 on 2023-07-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reservationcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_date', models.DateField(verbose_name='Date')),
                ('user_time', models.TimeField(verbose_name='Time')),
                ('user_count', models.IntegerField(verbose_name='Count')),
                ('user_message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
