# Generated by Django 4.2.3 on 2023-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_phone',
            field=models.CharField(default=1, max_length=25, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
