# Generated by Django 4.2.3 on 2023-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_reservation_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='', verbose_name='Image 1')),
                ('img2', models.ImageField(upload_to='', verbose_name='Image 2')),
                ('img3', models.ImageField(upload_to='', verbose_name='Image 3')),
                ('img4', models.ImageField(upload_to='', verbose_name='Image 4')),
                ('img5', models.ImageField(upload_to='', verbose_name='Image 5')),
                ('img6', models.ImageField(upload_to='', verbose_name='Image 6')),
                ('img7', models.ImageField(upload_to='', verbose_name='Image 7')),
                ('img8', models.ImageField(upload_to='', verbose_name='Image 8')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
