# Generated by Django 4.2.3 on 2023-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession')),
                ('profession_ru', models.CharField(max_length=50, null=True, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=50, null=True, verbose_name='Profession')),
                ('social1', models.CharField(max_length=50, verbose_name='Social Icon 1')),
                ('social_url1', models.URLField(verbose_name='Social Url 1')),
                ('social2', models.CharField(max_length=50, verbose_name='Social Icon 2')),
                ('social_url2', models.URLField(verbose_name='Social Url 2')),
                ('social3', models.CharField(max_length=50, verbose_name='Social Icon 3')),
                ('social_url3', models.URLField(verbose_name='Social Url 3')),
                ('social4', models.CharField(max_length=50, verbose_name='Social Icon 4')),
                ('social_url4', models.URLField(verbose_name='Social Url 4')),
            ],
        ),
    ]
