# Generated by Django 4.2.3 on 2023-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map', models.TextField(verbose_name='Google Map')),
                ('placeholder1', models.CharField(max_length=50, verbose_name='Input Placeholder 1')),
                ('placeholder1_ru', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 1')),
                ('placeholder1_en', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 1')),
                ('placeholder2', models.CharField(max_length=50, verbose_name='Input Placeholder 2')),
                ('placeholder2_ru', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 2')),
                ('placeholder2_en', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 2')),
                ('placeholder3', models.CharField(max_length=50, verbose_name='Input Placeholder 3')),
                ('placeholder3_ru', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 3')),
                ('placeholder3_en', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 3')),
                ('placeholder4', models.CharField(max_length=50, verbose_name='Input Placeholder 4')),
                ('placeholder4_ru', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 4')),
                ('placeholder4_en', models.CharField(max_length=50, null=True, verbose_name='Input Placeholder 4')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('btn_name_ru', models.CharField(max_length=40, null=True, verbose_name='Button Name')),
                ('btn_name_en', models.CharField(max_length=40, null=True, verbose_name='Button Name')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
