# Generated by Django 4.2.3 on 2023-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=40, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=40, null=True, verbose_name='Title')),
                ('info', models.CharField(max_length=100, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
